### PR TITLE
Add AI and blockchain to project

### PR DESCRIPTION
**Pull request by itsAmr**
If true else false 

Please review thoroughly

thank you next

### CODE REVIEW

**Review by malhotraguy — COMMENTED** [review]
H,mmmmm.. New Technologies... Brilliant Work!!!!

**Review by jaimeandreshernandez — CHANGES_REQUESTED** [review]
bruh.

**Review by mari3mmi — COMMENTED** [review]
needs more ai.html

**Comment by itsAmr** [comment]
Thanks for the feedback guys !! WERKING ON ITT

**Pull request closed without merging**
